POST http://localhost:8080/expenses
Content-Type: application/json

{"amount": 24.50, "category": "food", "note": "Lunch", "spent_on": "2026-05-08"}

### 
GET http://localhost:8080/expenses

### Existing id
GET http://localhost:8080/expenses/df2c7745-5e5e-4f4c-a9bb-a7c3ba82c7a0

### Non-existing id  
GET http://localhost:8080/expenses/00000000-0000-0000-0000-000000000000